[package]
name = "ferveo-python"
authors = ["Piotr Roslaniec <p.roslaniec@gmail.com>"]
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["macros"] }
ferveo = { path = "../ferveo" }
group-threshold-cryptography = { path = "../tpke" }
derive_more = { version = "0.99", default-features = false, features = ["from", "as_ref"] }
rand = "0.8"

[build-dependencies]
pyo3-build-config = "*"
